import {readdir,readFile,writeFile,mkdir} from 'node:fs/promises';
import {renderMarkdown,renderInline,hasMath,hasMermaid,KATEX_CSS} from './render.mjs';
import {sectionsOf,leadKeyOf} from './schema.mjs';
const root=new URL('../',import.meta.url);const catalog=JSON.parse(await readFile(new URL('data/catalog.json',root),'utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const layout=(title,path,body,description='汇集每日定时学习内容的结构化知识站',headExtra='')=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><title>${esc(title)}｜每日学习库</title><link rel="stylesheet" href="${path}assets/styles.css"><link rel="stylesheet" href="${path}assets/hub.css">${headExtra}</head><body><header class="shell site-head"><a class="brand" href="${path}index.html">每日学习库</a><nav class="head-links"><a href="${path}index.html#collections">学习专题</a><a href="${path}index.html#lessons">全部内容</a></nav></header>${body}<footer><div class="shell">结构化数据是唯一事实源 · 让每一次定时学习持续积累</div></footer></body></html>`;
const bundles=[];
for(const track of catalog){const dataDir=new URL(`data/${track.key}/`,root);const files=(await readdir(dataDir)).filter(x=>/^[A-Z]+-D\d{3}\.json$/.test(x)).sort();const courses=[];for(const file of files)courses.push(JSON.parse(await readFile(new URL(file,dataDir),'utf8')));await writeFile(new URL('index.json',dataDir),JSON.stringify(courses,null,2)+'\n');bundles.push({track,courses});}
const cards=bundles.map(({track,courses})=>`<a class="collection-card" href="./classics/${track.slug}/index.html"><div class="eyebrow">${esc(track.category)} · ${courses.length} 课</div><h2>${esc(track.title)}</h2><p>${esc(track.description)}</p></a>`).join('');
await writeFile(new URL('index.html',root),layout('首页','',`<main><section class="shell hero"><div><div class="eyebrow">Daily Learning · Knowledge Hub</div><h1>每日所学<br>汇流成河</h1><p class="hero-copy">统一收集每个定时学习任务的内容。每个专题独立生长，共享搜索、索引与知识结构。</p></div><div class="seal">日积<br>月累</div></section><section class="shell stats"><div class="stat"><b data-tracks>—</b><span>学习专题</span></div><div class="stat"><b data-done>—</b><span>已完成内容</span></div><div class="stat"><b data-total>—</b><span>内容总数</span></div></section><section class="shell workspace" id="collections"><h2 class="section-title">学习专题</h2><div class="collection-grid">${cards}</div><div class="tools" id="lessons"><h2>全部内容</h2><input class="search" data-search type="search" placeholder="搜索专题、标题、章节或关键词" aria-label="搜索全部学习内容"></div><div class="course-list" data-course-list><div class="empty">正在读取学习内容…</div></div></section></main><script src="./assets/app.js" defer></script>`));
const mermaidHead=`<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js" defer></script><script>addEventListener('DOMContentLoaded',()=>{mermaid.initialize({startOnLoad:true});});</script>`;
const katexHead=`<link rel="stylesheet" href="${KATEX_CSS}">`;
const diagramsHtml=c=>{const d=c.extensions?.diagrams;return Array.isArray(d)&&d.length?`<section class="lesson-section" id="diagrams"><h2>图解</h2>${d.map(x=>`<h3>${esc(x.title??'')}</h3><pre class="mermaid">${esc(x.code??'')}</pre>`).join('')}</section>`:'';};
for(const {track,courses} of bundles){const labels=sectionsOf(track);const base=`classics/${track.slug}/`;for(const dir of ['days','weekly','monthly'])await mkdir(new URL(`${base}${dir}/`,root),{recursive:true});const list=courses.map(c=>`<a class="course-card" href="./days/${c.id}.html"><span class="course-id">${c.id}</span><span><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p></span><span class="arrow">→</span></a>`).join('');await writeFile(new URL(`${base}index.html`,root),layout(track.title,'../../',`<main class="shell"><div class="breadcrumb"><a href="../../index.html">每日学习库</a> › ${esc(track.shortTitle)}</div><header class="entry-head"><div class="eyebrow">${esc(track.category)}</div><h1>${esc(track.title)}</h1><p class="hero-copy">${esc(track.description)}</p></header><section class="workspace"><div class="tools"><h2>课程目录</h2><nav class="head-links"><a href="./weekly/index.html">周索引</a><a href="./monthly/index.html">知识树</a></nav></div><div class="course-list">${list}</div></section></main>`,track.description));
for(let i=0;i<courses.length;i++){const c=courses[i],prev=courses[i-1],next=courses[i+1];const sections=labels.map(([key,label])=>{const v=c.sections[key];const content=Array.isArray(v)?`<ol>${v.map(x=>`<li>${renderInline(x)}</li>`).join('')}</ol>`:`<div class="markdown-body ${key===leadKeyOf(track)?'original':''}">${renderMarkdown(v)}</div>`;return `<section class="lesson-section" id="${key}"><h2>${label}</h2>${content}</section>`}).join('');const toc=labels.map(([key,label])=>`<a href="#${key}">${label}</a>`).join('');const nav=`<nav class="lesson-nav">${prev?`<a href="${prev.id}.html">← ${esc(prev.title)}</a>`:'<span></span>'}<a href="../index.html">返回专题目录</a>${next?`<a href="${next.id}.html">${esc(next.title)} →</a>`:'<span></span>'}</nav>`;const body=`<main class="shell"><div class="breadcrumb"><a href="../../../index.html">每日学习库</a> › <a href="../index.html">${esc(track.shortTitle)}</a> › ${c.id}</div><header class="entry-head"><div class="eyebrow">${c.id}</div><h1>${esc(c.title)}</h1><div class="meta">${esc(c.chapter)} · ${esc(c.date)} · ${c.keywords.map(esc).join(' / ')}</div></header><div class="entry-grid"><aside class="toc">${toc}</aside><article><p class="hero-copy">${esc(c.summary)}</p>${sections}${diagramsHtml(c)}${nav}</article></div></main>`;const sectionValues=Object.values(c.sections??{}).flat();const needsMermaid=(Array.isArray(c.extensions?.diagrams)&&c.extensions.diagrams.length)||sectionValues.some(hasMermaid);await writeFile(new URL(`${base}days/${c.id}.html`,root),layout(c.title,'../../../',body,c.summary,(needsMermaid?mermaidHead:'')+(sectionValues.some(hasMath)?katexHead:'')));}
const weeks=[];for(let i=0;i<courses.length;i+=7)weeks.push(courses.slice(i,i+7));const weekly=`<main class="shell"><div class="breadcrumb"><a href="../index.html">${esc(track.title)}</a> › 周索引</div><header class="entry-head"><div class="eyebrow">Weekly Review</div><h1>周索引</h1></header><div class="hub-grid">${weeks.map((w,i)=>`<section class="hub-card"><div class="eyebrow">Week ${i+1}</div><h2>${w[0].id}—${w.at(-1).id}</h2>${w.map(c=>`<p><a href="../days/${c.id}.html">${c.id}｜${esc(c.title)}</a></p>`).join('')}</section>`).join('')}</div></main>`;await writeFile(new URL(`${base}weekly/index.html`,root),layout(`${track.shortTitle}周索引`,'../../../',weekly));const groups=Map.groupBy(courses,c=>c.chapter);const monthly=`<main class="shell"><div class="breadcrumb"><a href="../index.html">${esc(track.title)}</a> › 知识树</div><header class="entry-head"><div class="eyebrow">Knowledge Tree</div><h1>知识树</h1></header><div class="hub-grid">${[...groups].map(([chapter,items])=>`<section class="hub-card"><div class="eyebrow">${items.length} 课</div><h2>${esc(chapter)}</h2><p>${[...new Set(items.flatMap(x=>x.keywords))].map(esc).join(' · ')}</p>${items.map(c=>`<p><a href="../days/${c.id}.html">${c.id}｜${esc(c.title)}</a></p>`).join('')}</section>`).join('')}</div></main>`;await writeFile(new URL(`${base}monthly/index.html`,root),layout(`${track.shortTitle}知识树`,'../../../',monthly));}
const first=bundles[0];if(first){await mkdir(new URL('days/',root),{recursive:true});for(const c of first.courses)await writeFile(new URL(`days/${c.id}.html`,root),`<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../classics/${first.track.slug}/days/${c.id}.html"><title>页面已迁移</title><a href="../classics/${first.track.slug}/days/${c.id}.html">前往新页面</a>`);}
console.log(`Built ${bundles.length} learning tracks and ${bundles.reduce((n,x)=>n+x.courses.length,0)} lessons.`);
