import {readFile,access,readdir} from 'node:fs/promises';
const yijingOrder=['乾','坤','屯','蒙','需','讼','师','比','小畜','履','泰','否','同人','大有','谦','豫','随','蛊','临','观','噬嗑','贲','剥','复','无妄','大畜','颐','大过','坎','离','咸','恒','遁','大壮','晋','明夷','家人','睽','蹇','解','损','益','夬','姤','萃','升','困','井','革','鼎','震','艮','渐','归妹','丰','旅','巽','兑','涣','节','中孚','小过','既济','未济'];
const catalogForCurricula=JSON.parse(await readFile(new URL('data/catalog.json',new URL('../',import.meta.url))));
for(const track of catalogForCurricula.filter(item=>item.curriculum)){
  const dataDir=new URL(`data/${track.key}/`,new URL('../',import.meta.url));
  const curriculum=JSON.parse(await readFile(new URL(track.curriculum,dataDir)));
  const sourceFiles=(await readdir(dataDir)).filter(file=>/^[A-Z]+-D\d{3}\.json$/.test(file)).sort();
  for(let i=0;i<sourceFiles.length;i++){
    const course=JSON.parse(await readFile(new URL(sourceFiles[i],dataDir)));
    if(course.title!==curriculum[i]||course.extensions?.curriculum?.ordinal!==i+1||course.extensions?.curriculum?.topic!==curriculum[i])throw new Error(`${course.id} 必须对应课程顺序第 ${i+1} 课“${curriculum[i]}”`);
  }
}
const root=new URL('../',import.meta.url);const catalog=JSON.parse(await readFile(new URL('data/catalog.json',root)));if(!catalog.length)throw new Error('学习目录为空');let total=0;const trackKeys=new Set(),trackSlugs=new Set();for(const track of catalog){for(const k of ['key','slug','title','shortTitle','description','category','status'])if(!(k in track))throw new Error(`${track.key} 缺少 ${k}`);if(trackKeys.has(track.key)||trackSlugs.has(track.slug))throw new Error(`专题 key 或 slug 重复：${track.key}`);trackKeys.add(track.key);trackSlugs.add(track.slug);const dataDir=new URL(`data/${track.key}/`,root);const sourceFiles=(await readdir(dataDir)).filter(file=>/^[A-Z]+-D\d{3}\.json$/.test(file)).sort();const courses=JSON.parse(await readFile(new URL('index.json',dataDir)));if(!courses.length)throw new Error(`${track.key} 没有课程`);if(sourceFiles.length!==courses.length)throw new Error(`${track.key} index.json 与课程源文件数量不一致，请先运行 npm run build`);total+=courses.length;const ids=new Set();const expectedPrefix=track.prefix??sourceFiles[0]?.match(/^([A-Z]+)-D/)[1];for(let i=0;i<courses.length;i++){const c=courses[i];for(const k of ['schemaVersion','work','id','title','date','status','chapter','keywords','summary','sections'])if(!(k in c))throw new Error(`${c.id} 缺少 ${k}`);if(c.schemaVersion!==1)throw new Error(`${c.id} schemaVersion 必须为 1`);if(c.work!==track.slug)throw new Error(`${c.id} work 必须为 ${track.slug}`);if(ids.has(c.id))throw new Error(`${track.key} 课程 ID 重复：${c.id}`);ids.add(c.id);const expectedId=`${expectedPrefix}-D${String(i+1).padStart(3,'0')}`;if(c.id!==expectedId||sourceFiles[i]!==`${expectedId}.json`)throw new Error(`${track.key} 课程必须从 D001 连续编号；预期 ${expectedId}`);if(track.key==='yijing'&&(c.extensions?.hexagram?.ordinal!==i+1||c.extensions?.hexagram?.name!==yijingOrder[i]))throw new Error(`${c.id} 必须对应六十四卦第 ${i+1} 卦“${yijingOrder[i]}”`);if(!Array.isArray(c.keywords)||!c.keywords.length)throw new Error(`${c.id} keywords 不能为空`);for(const section of ['original','explanation','coreIdea','connections','applications','reflection','questions','mastery'])if(!(section in c.sections))throw new Error(`${c.id} sections 缺少 ${section}`);await access(new URL(`classics/${track.slug}/days/${c.id}.html`,root));}for(const f of [`classics/${track.slug}/index.html`,`classics/${track.slug}/weekly/index.html`,`classics/${track.slug}/monthly/index.html`])await access(new URL(f,root));}for(const f of ['index.html','assets/styles.css','assets/hub.css','assets/app.js'])await access(new URL(f,root));console.log(`Checked ${catalog.length} learning tracks and ${total} lessons.`);
